site_name: 山脇様の実験室
theme:
  name: material
  favicon: img/favicon
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
  palette: # (1)!
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 # (2)!
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple

plugins:
  - search

search:
  exclude: true

nav:
  - Home: index.md
  - Oort Cloud: music.md
  - Getting started:
      - Installation: oortCloud.md
      - Creating your site: Arifureta_Battle_song
      - Publishing your site: publishing-your-site.md
      - Customization: customization.md
      - Conventions: conventions.md
      - Browser support: browser-support.md
      - Enterprise feedback: enterprise-support.md
      - Philosophy: philosophy.md
      - Alternatives: alternatives.md
      - License: license.md
      - Tutorials:
          - tutorials/index.md
          - "Blogs":
              - tutorials/blogs/basic.md
              - tutorials/blogs/navigation.md
              - tutorials/blogs/engage.md
          - "Social cards":
              - tutorials/social/basic.md
              - tutorials/social/custom.md
      - Changelog:
          - changelog/index.md
          - How to upgrade: upgrade.md
  - Setup:
      - setup/index.md
      - Changing the colors: setup/changing-the-colors.md
      - Changing the fonts: setup/changing-the-fonts.md
      - Changing the language: setup/changing-the-language.md
      - Changing the logo and icons: setup/changing-the-logo-and-icons.md
      - Ensuring data privacy: setup/ensuring-data-privacy.md
      - Setting up navigation: setup/setting-up-navigation.md
      - Setting up site search: setup/setting-up-site-search.md
      - Setting up site analytics: setup/setting-up-site-analytics.md
      - Setting up social cards: setup/setting-up-social-cards.md
      - Setting up a blog: setup/setting-up-a-blog.md
      - Setting up tags: setup/setting-up-tags.md
      - Setting up versioning: setup/setting-up-versioning.md
      - Setting up the header: setup/setting-up-the-header.md
      - Setting up the footer: setup/setting-up-the-footer.md
      - Adding a git repository: setup/adding-a-git-repository.md
      - Adding a comment system: setup/adding-a-comment-system.md
      - Building an optimized site: setup/building-an-optimized-site.md
      - Building for offline usage: setup/building-for-offline-usage.md
      - Extensions:
          - setup/extensions/index.md
          - Python Markdown: setup/extensions/python-markdown.md
          - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  - Plugins:
      - plugins/index.md
      - Blog: plugins/blog.md
      - Group: plugins/group.md
      - Info: plugins/info.md
      - Meta: plugins/meta.md
      - Offline: plugins/offline.md
      - Optimize: plugins/optimize.md
      - Privacy: plugins/privacy.md
      - Projects: plugins/projects.md
      - Search: plugins/search.md
      - Social: plugins/social.md
      - Tags: plugins/tags.md
      - Typeset: plugins/typeset.md
      - Requirements:
          - Image processing: plugins/requirements/image-processing.md
          - Caching: plugins/requirements/caching.md
  - Reference:
      - reference/index.md
      - Admonitions: reference/admonitions.md
      - Annotations: reference/annotations.md
      - Buttons: reference/buttons.md
      - Code blocks: reference/code-blocks.md
      - Content tabs: reference/content-tabs.md
      - Data tables: reference/data-tables.md
      - Diagrams: reference/diagrams.md
      - Footnotes: reference/footnotes.md
      - Formatting: reference/formatting.md
      - Grids: reference/grids.md
      - Icons, Emojis: reference/icons-emojis.md
      - Images: reference/images.md
      - Lists: reference/lists.md
      - Math: reference/math.md
      - Tooltips: reference/tooltips.md
  - Insiders:
      - insiders/index.md
      - Why sponsor us: insiders/why-sponsor-us.md
      - What's in it for you: insiders/benefits.md
      - Who is sponsoring: insiders/our-sponsors.md
      - Sponsoring tiers: insiders/sponsoring-tiers.md
      - How to sponsor: insiders/how-to-sponsor.md
      - Additional information:
          - Payment and billing: insiders/payment-and-billing.md
          - Access management: insiders/access-management.md
          - Runtime and cancellation: insiders/runtime-and-cancellation.md
          - Privacy: insiders/privacy.md
          - License: insiders/license.md
          - Support: support.md
      - Using Insiders:
          - Getting started: insiders/getting-started.md
      - Changelog:
          - insiders/changelog/index.md
          - How to upgrade: insiders/upgrade.md
  - Community:
      - Contributing:
          - contributing/index.md
          - Reporting a bug: contributing/reporting-a-bug.md
          - Reporting a docs issue: contributing/reporting-a-docs-issue.md
          - Requesting a change: contributing/requesting-a-change.md
          - Adding translations: contributing/adding-translations.md
          - Making a pull request: contributing/making-a-pull-request.md
          - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
      - Guides:
          - Creating a reproduction: guides/creating-a-reproduction.md
      - Community experts program:
          - insiders/community-experts-program/index.md
  - Blog:
      - blog/index.md
